---
booktitle: Proceedings of The First Workshop Medical Informatics and Healthcare held
  with the 23rd SIGKDD Conference on Knowledge Discovery and Data Mining
shortname: MIH'17
volume: 69
year: '2017'
start: 2017-08-14
end: 2017-08-14
url: http://proceedings.mlr.press
author:
  name: PMLR
location: Nova Scotia, Halifax, Canada
published: 2017-10-18
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: ICE-2017
month: 0
cycles: false
editor:
- given: Samah
  family: Fodeh
- given: Daniela Stan
  family: Raicu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The First Workshop Medical Informatics and Healthcare held with the 23rd SIGKDD Conference on Knowledge Discovery and Data Mining on 14 August 2017

  Published as Volume 69 by the Proceedings of Machine Learning Research on 18 October 2017.

  Volume Edited by:
    Samah Fodeh
    Daniela Stan Raicu

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 14 Aug
baseurl: "/v69"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v69
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Medical Informatics and Healthcare
  url: 
  location: 
  dates:
  - 2017-08-14
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
